import { userType } from "./Types";

export const dummyUser: userType[] = [
  {
    id: "1",
    name: "Mahmud Hasan",
    email: "mahmud1@example.com",
    phone: "01710000001",
    address: "Dhanmondi, Dhaka",
    isVerified: true,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=1",
    lastMessage: "Hello",
  },
  {
    id: "2",
    name: "Rakib Hossain",
    email: "rakib2@example.com",
    phone: "01710000002",
    address: "Mirpur, Dhaka",
    isVerified: true,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=2",
    lastMessage: "Hello",
  },
  {
    id: "3",
    name: "Nusrat Jahan",
    email: "nusrat3@example.com",
    phone: "01710000003",
    address: "Uttara, Dhaka",
    isVerified: false,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=3",
  },
  {
    id: "4",
    name: "Tanvir Ahmed",
    email: "tanvir4@example.com",
    phone: "01710000004",
    address: "Banani, Dhaka",
    isVerified: true,
    block: true,
    avatar: "https://i.pravatar.cc/150?img=4",
  },
  {
    id: "5",
    name: "Sumaiya Islam",
    email: "sumaiya5@example.com",
    phone: "01710000005",
    address: "Mohammadpur, Dhaka",
    isVerified: false,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: "6",
    name: "Sabbir Khan",
    email: "sabbir6@example.com",
    phone: "01710000006",
    address: "Gazipur",
    isVerified: true,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=6",
  },
  {
    id: "7",
    name: "Jannat Mim",
    email: "jannat7@example.com",
    phone: "01710000007",
    address: "Narayanganj",
    isVerified: true,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=7",
  },
  {
    id: "8",
    name: "Mehedi Hasan",
    email: "mehedi8@example.com",
    phone: "01710000008",
    address: "Cumilla",
    isVerified: false,
    block: true,
    avatar: "https://i.pravatar.cc/150?img=8",
  },
  {
    id: "9",
    name: "Priya Sarker",
    email: "priya9@example.com",
    phone: "01710000009",
    address: "Chattogram",
    isVerified: true,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=9",
  },
  {
    id: "10",
    name: "Arif Rahman",
    email: "arif10@example.com",
    phone: "01710000010",
    address: "Sylhet",
    isVerified: false,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=10",
  },
  {
    id: "11",
    name: "Rifat Karim",
    email: "rifat11@example.com",
    phone: "01710000011",
    address: "Khulna",
    isVerified: true,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=11",
  },
  {
    id: "12",
    name: "Mim Akter",
    email: "mim12@example.com",
    phone: "01710000012",
    address: "Rajshahi",
    isVerified: true,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: "13",
    name: "Shakib Alif",
    email: "shakib13@example.com",
    phone: "01710000013",
    address: "Barishal",
    isVerified: false,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=13",
  },
  {
    id: "14",
    name: "Tania Rahman",
    email: "tania14@example.com",
    phone: "01710000014",
    address: "Rangpur",
    isVerified: true,
    block: true,
    avatar: "https://i.pravatar.cc/150?img=14",
  },
  {
    id: "15",
    name: "Hasib Chowdhury",
    email: "hasib15@example.com",
    phone: "01710000015",
    address: "Mymensingh",
    isVerified: true,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=15",
  },
  {
    id: "16",
    name: "Anika Noor",
    email: "anika16@example.com",
    phone: "01710000016",
    address: "Pabna",
    isVerified: false,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=16",
  },
  {
    id: "17",
    name: "Siam Ahmed",
    email: "siam17@example.com",
    phone: "01710000017",
    address: "Jessore",
    isVerified: true,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=17",
  },
  {
    id: "18",
    name: "Farzana Islam",
    email: "farzana18@example.com",
    phone: "01710000018",
    address: "Bogura",
    isVerified: true,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=18",
  },
  {
    id: "19",
    name: "Nahid Hasan",
    email: "nahid19@example.com",
    phone: "01710000019",
    address: "Tangail",
    isVerified: false,
    block: true,
    avatar: "https://i.pravatar.cc/150?img=19",
  },
  {
    id: "20",
    name: "Sharmin Sultana",
    email: "sharmin20@example.com",
    phone: "01710000020",
    address: "Noakhali",
    isVerified: true,
    block: false,
    avatar: "https://i.pravatar.cc/150?img=20",
  },
];
